#!/bin/sh

# Colors
NC='\033[0m'
BBlue='\033[1;34m'
BRed='\033[1;33m'

echo "\n${BRed}Do you want to install the Javascript Quality tools? (Y/y for yes or anything else for no)${NC}"
read JSPACKAGES
JSPACKAGES=$(uppercase $JSPACKAGES)