#!/bin/sh

# Colors
NC='\033[0m'
BBlue='\033[1;34m'
BRed='\033[1;33m'

PACKAGES=''
ISNUXT=$(npm list | grep -q "nuxt")

if $ISNUXT; then
    PACKAGES='eslint-plugin-nuxt eslint-plugin-vue @nuxtjs/eslint-config-typescript'
fi

echo "\n${BBlue}Installing dev dependencies${NC}"
npm install -D prettier eslint eslint-config-prettier cypress $(echo $PACKAGES)

echo "\n${BBlue}Copying configuration files${NC}"
echo "\n${BRed}1. Prettier${NC}"
curl -s -o .prettierignore "https://raw.githubusercontent.com/elitedevsquad/devsquad-setup-front/master/verification-tools/.prettierignore"
curl -s -o .prettierrc "https://raw.githubusercontent.com/elitedevsquad/devsquad-setup-front/master/verification-tools/.prettierrc"

echo "\n${BRed}2. Eslint${NC}"
if $ISNUXT; then
  curl -s -o .eslintrc.js "https://raw.githubusercontent.com/elitedevsquad/devsquad-setup-front/master/verification-tools/.eslintrc-nuxt.js"
else
  curl -s -o .eslintrc.js "https://raw.githubusercontent.com/elitedevsquad/devsquad-setup-front/master/verification-tools/.eslintrc.js"
fi

echo "\n${BRed}3. Cypress${NC}"
mkdir "cypress"
mkdir "cypress/downloads"
mkdir "cypress/e2e"
mkdir "cypress/fixtures"
mkdir "cypress/support"
mkdir "cypress/videos"

curl -s -o cypress.config.ts "https://raw.githubusercontent.com/elitedevsquad/devsquad-setup-front/master/verification-tools/cypress.config.ts"
curl -s -o cypress/downloads/.gitkeep "https://raw.githubusercontent.com/elitedevsquad/devsquad-setup-front/master/verification-tools/cypress/downloads/.gitkeep"
curl -s -o cypress/e2e/example.cy.ts "https://raw.githubusercontent.com/elitedevsquad/devsquad-setup-front/master/verification-tools/cypress/e2e/example.cy.ts"
curl -s -o cypress/fixtures/example.json "https://raw.githubusercontent.com/elitedevsquad/devsquad-setup-front/master/verification-tools/cypress/fixtures/example.json"
curl -s -o cypress/support/commands.ts "https://raw.githubusercontent.com/elitedevsquad/devsquad-setup-front/master/verification-tools/cypress/support/commands.ts"
curl -s -o cypress/support/e2e.ts "https://raw.githubusercontent.com/elitedevsquad/devsquad-setup-front/master/verification-tools/cypress/support/e2e.ts"

echo "*
!.gitignore" > cypress/videos/.gitignore
