#!/bin/sh

# Colors
NC='\033[0m'
BBlue='\033[1;34m'
BRed='\033[1;33m'

PACKAGES=''
HASNUXT=$(npm list | grep -q "nuxt")

if [ $HASNUXT ]; then
    PACKAGES='eslint-plugin-nuxt eslint-plugin-vue @nuxtjs/eslint-config-typescript'
fi

echo "\n${BBlue}Installing dev dependencies${NC}"
npm install -D prettier eslint eslint-config-prettier $(echo $PACKAGES)

echo "\n${BBlue}Copying configuration files${NC}"
echo "\n${BRed}1. Prettier${NC}"
curl -s -o .prettierignore "https://raw.githubusercontent.com/elitedevsquad/devsquad-setup-front/master/verification-tools/.prettierignore"
curl -s -o .prettierrc "https://raw.githubusercontent.com/elitedevsquad/devsquad-setup-front/master/verification-tools/.prettierrc"

echo "\n${BRed}2. Eslint${NC}"
curl -s -o .eslintrc.js "https://raw.githubusercontent.com/elitedevsquad/devsquad-setup-front/master/verification-tools/.eslintrc.js"