#!/bin/sh

NC='\033[0m'
BBlue='\033[1;34m'
BRed='\033[1;31m'

NAME=$(git branch | grep '*' | sed 's/* //')
echo "Running pre-push hook on: ${BBlue}" $NAME "${NC}"

# ----------------------------------------------------------------------------------------
# 1. Prettier
echo "${BBlue}1. Prettier${NC}"
npm run style:check

STATUS_CODE=$?
if [ $STATUS_CODE -ne 0 ]; then
    echo "${BRed}1.... prettier${NC}"
    exit 1
fi

# ----------------------------------------------------------------------------------------
# 2. ESLint
echo "${BBlue}2. ESLint${NC}"
npm run lint

STATUS_CODE=$?
if [ $STATUS_CODE -ne 0 ]; then
    echo "${BRed}2.... eslint${NC}"
    exit 1
fi

# ----------------------------------------------------------------------------------------
# 4. Tests
echo "${BBlue}4. Running Tests${NC}"